projects:
  burnedoverdevAppSyncAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: nordqjk7abcatodpk3f5633aqm
        maxDepth: 3
extensions:
  amplify:
    version: 3
